os: linux
language: python
python:
  - '3.5'
  - '3.6'
install:
  - sudo apt-get update
  - sudo apt-get install -y check
  - pip install numpy
script:
  - make -C c_src test
  - python setup.py sdist
  - python setup.py bdist_wheel
  - pip install dist/lyon*.whl
  - python examples/lyon_examples.py
